;;;; src/parser.lisp
(in-package #:cl-regex-kit)

(defun parse-regex (pattern &key (initial-flags +flag-unicode+)
                                  byte-mode
                                  literal
                                  never-capture
                                  (octal t)
                                  (nest-limit +default-nest-limit+)
                                  (line-terminator #\Newline))
  "Parse PATTERN into a REGEX-NODE tree.
Signals REGEX-SYNTAX-ERROR on malformed input."
  (unless (stringp pattern)
    (error 'regex-syntax-error :pattern pattern :reason "Pattern must be a string"))
  (check-type initial-flags (integer 0 *))
  (check-type byte-mode boolean)
  (check-type literal boolean)
  (check-type never-capture boolean)
  (check-type octal boolean)
  (check-type nest-limit (integer 0 *))
  (check-type line-terminator character)
  (let ((position 0)
        (length (length pattern))
        (group-count 0)
        (group-names nil)
        (flags initial-flags)
        (nesting-depth 0))
    (labels ((fail (reason &optional (at position))
               (error 'regex-syntax-error :pattern pattern :position at :reason reason))
             (at-end-p () (>= position length))
             (raw-peek () (and (not (at-end-p)) (char pattern position)))
             (skip-extended-syntax ()
               (when (logtest +flag-extended+ flags)
                 (loop
                   (loop while (and (raw-peek) (sb-unicode:whitespace-p (raw-peek))) do
                     (incf position))
                   (if (and (raw-peek)
                            (char= (raw-peek) #\#))
                       (progn
                         (loop while (and (raw-peek) (not (char= (raw-peek) #\Newline))) do
                           (incf position))
                         (when (raw-peek) (incf position)))
                       (return)))))
             (peek ()
               (skip-extended-syntax)
               (raw-peek))
             (raw-take ()
               (if (at-end-p)
                   (fail "Unexpected end of pattern")
                   (prog1 (char pattern position) (incf position))))
             (take ()
               (let ((character (peek)))
                 (if character
                     (prog1 character (incf position))
                     (fail "Unexpected end of pattern"))))
             (flag-p (flag) (logtest flag flags))
             (ensure-byte-character (character)
               (when (and byte-mode (not (flag-p +flag-unicode+))
                          (> (char-code character) #xff))
                 (fail "Byte patterns only accept code points in the range 0..255"))
               character)
             (ensure-byte-class-character (character raw-octet-p)
               (when (and byte-mode (not (flag-p +flag-unicode+))
                          (not raw-octet-p) (> (char-code character) #x7f))
                 (fail "Unicode is not allowed in a non-Unicode byte character class"))
               (ensure-byte-character character))
             (make-literal (character &key raw-octet-p)
               (make-instance 'literal-node :char character
                              :raw-octet-p raw-octet-p
                              :case-insensitive-p (flag-p +flag-case-insensitive+)
                              :unicode-p (flag-p +flag-unicode+)))
             (byte-matcher-p (matcher)
               (case (first matcher)
                 (:ranges (every (lambda (range) (<= (cdr range) #xff)) (second matcher)))
                 (:property nil)
                 (:negate (byte-matcher-p (second matcher)))
                 ((:union :intersection :difference :symmetric-difference)
                  (every #'byte-matcher-p (rest matcher)))
                 (otherwise nil)))
             (make-class (ranges &optional negated-p matcher)
               (when (and byte-mode (not (flag-p +flag-unicode+)) matcher
                          (not (byte-matcher-p matcher)))
                 (fail "Unicode character classes are not available in byte patterns"))
               (make-instance 'char-class-node :ranges ranges :matcher matcher :negated-p negated-p
                              :case-insensitive-p (flag-p +flag-case-insensitive+)
                              :unicode-p (flag-p +flag-unicode+)))
             (make-concat (children)
               (cond ((null children) (make-instance 'concat-node :children nil))
                     ((null (cdr children)) (car children))
                     (t (make-instance 'concat-node :children children))))
             (digit-p (character) (and character (digit-char-p character)))
             (take-while (predicate)
               (let ((characters nil))
                 (loop while (and (peek) (funcall predicate (peek))) do
                   (push (take) characters))
                 (coerce (nreverse characters) 'string)))
             (parse-number ()
               (let ((beginning position))
                 (unless (digit-p (peek))
                   (fail "Expected a decimal number"))
                 (let ((count (parse-integer (take-while #'digit-p))))
                   (when (> count +maximum-repeat-count+)
                     (fail "Repetition count exceeds 1000" beginning))
                   count)))
             (range (start end)
               (ensure-byte-character start)
               (ensure-byte-character end)
               (cons (char-code start) (char-code end)))
             (shorthand-ranges (character)
               (case character
                 ((#\d #\D) (list (range #\0 #\9)))
                 ((#\w #\W) (list (range #\a #\z) (range #\A #\Z)
                                    (range #\0 #\9) (range #\_ #\_)))
                 ((#\s #\S) (list (range #\Space #\Space) (range #\Tab #\Tab)
                                    (range #\Newline #\Newline) (range #\Return #\Return)
                                    (range #\Page #\Page)
                                    (range (code-char 11) (code-char 11))))
                 (otherwise nil)))
             (shorthand-matcher (character)
               (if (flag-p +flag-unicode+)
                   (case character
                     ((#\d #\D) '(:property "Nd"))
                     ((#\w #\W) '(:union (:property "Alphabetic") (:property "Mark")
                                           (:property "Nd") (:property "Pc")
                                           (:ranges ((95 . 95) (#x200c . #x200d)))))
                     ((#\s #\S) '(:property "White_Space"))
                     (otherwise nil))
                   (let ((ranges (shorthand-ranges character)))
                     (and ranges (list :ranges ranges)))) )
             (parse-unicode-property ()
               (if (and (peek) (char= (peek) #\{))
                   (progn
                     (take)
                      (let ((beginning position)
                            (name (take-while
                                   (lambda (character)
                                     (not (char= character #\}))))))
                        (when (zerop (length name))
                          (fail "Unicode property name cannot be empty"))
                        (unless (peek)
                          (fail "Unclosed Unicode property"))
                        (let ((not-equal-position (search "!=" name))
                              (separator-position nil)
                              (negated-p nil))
                          (cond
                            (not-equal-position
                             (setf name
                                   (format nil "~A=~A"
                                           (subseq name 0 not-equal-position)
                                           (subseq name (+ not-equal-position 2)))
                                   negated-p t))
                            ((setf separator-position
                                   (or (position #\= name) (position #\: name)))
                             (setf name
                                   (format nil "~A=~A"
                                           (subseq name 0 separator-position)
                                           (subseq name (1+ separator-position))))))
                          (unless (unicode-property-name-p name)
                            (fail "Unknown or unsupported Unicode property" beginning))
                          (take)
                          (values name negated-p))))
                   (let ((beginning position)
                         (name (string (or (peek)
                                           (fail "Expected Unicode property name")))))
                     (take)
                     (unless (unicode-property-name-p name)
                       (fail "Unknown or unsupported Unicode property" beginning))
                     (values name nil))))
             (hex-digit-p (character) (and character (digit-char-p character 16)))
             (octal-digit-p (character) (and character (digit-char-p character 8)))
             (ascii-alphabetic-p (character)
               (and character
                    (or (and (char<= #\A character) (char<= character #\Z))
                        (and (char<= #\a character) (char<= character #\z)))))
             (ascii-alphanumeric-p (character)
               (and character
                    (or (ascii-alphabetic-p character)
                        (digit-char-p character))))
             (unicode-scalar-character (code beginning)
  (if (and (< code char-code-limit)
           (not (<= #xD800 code #xDFFF)))
      (code-char code)
      (fail "Unicode escape is not a Unicode scalar value" beginning)))
             (parse-hex-code (digits)
               (let ((beginning position))
                 (let ((hex (take-while #'hex-digit-p)))
                   (unless (= (length hex) digits)
                     (fail "Expected hexadecimal escape digits"))
                   (unicode-scalar-character
                    (parse-integer hex :radix 16)
                    beginning))))
             (parse-braced-hex-code ()
               (take)
               (let ((beginning position))
                 (let ((hex (take-while #'hex-digit-p)))
                   (when (zerop (length hex))
                     (fail "Expected hexadecimal escape digits"))
                   (unless (and (peek) (char= (peek) #\}))
                     (fail "Unclosed Unicode escape"))
                   (let ((code (parse-integer hex :radix 16)))
                     (take)
                     (unicode-scalar-character code beginning)))))
             (parse-octal-code (beginning)
               (loop repeat 2
                     while (octal-digit-p (raw-peek))
                     do (incf position))
               (let ((code (parse-integer pattern :start beginning :end position :radix 8)))
                 (unless (<= code #o377)
                   (fail "Octal escape is outside the byte range" beginning))
                 (code-char code)))
              (escaped-character ()
                (let ((escaped (raw-take)))
                  (case escaped
                    (#\a (code-char 7))
                    (#\f #\Page)
                    (#\n #\Newline)
                    (#\r #\Return)
                    (#\t #\Tab)
                    (#\v (code-char 11))
                    (#\x (let ((braced-p (and (peek) (char= (peek) #\{))))
                           (values
                            (if braced-p
                                (parse-braced-hex-code)
                                (ensure-byte-character (parse-hex-code 2)))
                            (and (not braced-p) (not (flag-p +flag-unicode+))))))
                    (#\u (if (and (peek) (char= (peek) #\{))
                             (parse-braced-hex-code)
                             (parse-hex-code 4)))
                    (#\U (if (and (peek) (char= (peek) #\{))
                             (parse-braced-hex-code)
                             (parse-hex-code 8)))
                    (otherwise escaped))))
             (parse-quoted-literal ()
               (let ((children nil))
                 (loop while (raw-peek) do
                    (if (and (char= (raw-peek) #\\)
                             (< (1+ position) length)
                             (char= (char pattern (1+ position)) #\E))
                        (progn
                          (incf position 2)
                          (return))
                        (push (make-literal (prog1 (raw-peek) (incf position))) children)))
                 (make-concat (nreverse children))))
             (word-anchor (kind)
               (make-instance 'anchor-node :kind kind
                               :unicode-p (flag-p +flag-unicode+)))
             (parse-word-boundary ()
               (if (and (peek) (char= (peek) #\{))
                   (let ((boundary-start position))
                     (take)
                     (let ((beginning position)
              (kind (take-while
                     (lambda (character)
                       (or (ascii-alphabetic-p character)
                           (char= character #\-))))))
                       ;; A non-boundary name leaves `{` for a repetition.
                       (if (zerop (length kind))
                           (progn
                             (setf position boundary-start)
                             (word-anchor :word-boundary))
                           (progn
                             (unless (and (peek) (char= (peek) #\}))
                               (fail "Unclosed word boundary" beginning))
                             (take)
                             (word-anchor
                              (cond ((string= kind "start") :word-start)
                                    ((string= kind "end") :word-end)
                                    ((string= kind "start-half") :word-start-half)
                                    ((string= kind "end-half") :word-end-half)
                                    (t (fail "Unknown word boundary" beginning))))))))
                   (word-anchor :word-boundary)))
             (parse-escape ()
              (let ((escaped (raw-take)))
                  (case escaped
                   ((#\A) (make-instance 'anchor-node :kind :absolute-start))
                   ((#\z) (make-instance 'anchor-node :kind :absolute-end))
                    ((#\b) (parse-word-boundary))
                    ((#\B) (make-instance 'anchor-node :kind :not-word-boundary
                                          :unicode-p (flag-p +flag-unicode+)))
                    ((#\<) (word-anchor :word-start))
                    ((#\>) (word-anchor :word-end))
                    (#\C
                     (unless byte-mode
                       (fail "\\C is only available in byte patterns" (1- position)))
                     (make-instance 'any-char-node :dotall-p t :crlf-p nil
                                    :line-terminator line-terminator :unicode-p nil))
                    ((#\p #\P)
                     (when (and byte-mode (not (flag-p +flag-unicode+)))
                       (fail "Unicode properties are not available in byte patterns" (1- position)))
                     (multiple-value-bind (property property-negated-p)
                         (parse-unicode-property)
                       (make-class nil (not (eq (char= escaped #\P) property-negated-p))
                                   (list :property property))))
                    (#\Q (parse-quoted-literal))
                    ((#\a #\f #\n #\r #\t #\v #\x #\u #\U)
                     (decf position)
                     (multiple-value-bind (character raw-octet-p)
                         (escaped-character)
                       (make-literal character :raw-octet-p raw-octet-p)))
                   ((#\d #\w #\s #\D #\W #\S)
                    (make-class nil (member escaped '(#\D #\W #\S))
                                (shorthand-matcher escaped)))
                   ((#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7)
                    (unless octal
                      (fail "Octal escapes are disabled" (1- position)))
                     (make-literal (parse-octal-code (1- position))
                                   :raw-octet-p (not (flag-p +flag-unicode+))))
                   ((#\8 #\9) (fail "Backreferences are not supported" (1- position)))
                   (otherwise
                    (when (ascii-alphanumeric-p escaped)
                      (fail "Invalid escape sequence" (1- position)))
                    (make-literal escaped)))))
             (ranges-matcher (ranges)
               (list :ranges ranges))
             (union-matcher (parts)
               (cond ((null parts) (ranges-matcher nil))
                     ((null (cdr parts)) (car parts))
                     (t (cons :union parts))))
             (node-matcher (node)
               (let ((matcher (or (char-class-node-matcher node)
                                  (ranges-matcher (char-class-node-ranges node)))))
                 (if (char-class-node-negated-p node)
                     (list :negate matcher)
                     matcher)))
             (posix-class-matcher (name negated-p)
               (let ((ranges
                       (ascii-posix-class-ranges (string-downcase name))))
                 (unless ranges
                   (fail "Unsupported POSIX character class"
                         (- position (length name) 3)))
                 (let ((matcher (ranges-matcher ranges)))
                   (if negated-p
                       (list :negate matcher)
                       matcher))))
             (parse-posix-class ()
               (unless (and (char= (peek) #\[)
                            (< (+ position 1) length)
                            (char= (char pattern (1+ position)) #\:))
                 (return-from parse-posix-class nil))
               (incf position 2)
               (let ((negated-p (and (char= (raw-peek) #\^)
                                     (prog1 t (incf position))))
                     (beginning position))
                 (loop while (and (raw-peek) (alpha-char-p (raw-peek))) do (incf position))
                 (when (= beginning position) (fail "POSIX character class name cannot be empty"))
                 (unless (and (raw-peek) (char= (raw-peek) #\:)
                              (< (1+ position) length)
                              (char= (char pattern (1+ position)) #\]))
                   (fail "Unclosed POSIX character class"))
                 (let ((name (subseq pattern beginning position)))
                   (incf position 2)
                   (posix-class-matcher name negated-p))))
             (class-item ()
               (if (char= (peek) #\\)
                   (progn
                     (take)
                   (let ((escaped (raw-take)))
                       (case escaped
                         ((#\p #\P)
                          (when (and byte-mode (not (flag-p +flag-unicode+)))
                            (fail "Unicode properties are not available in byte patterns" (1- position)))
                          (multiple-value-bind (property property-negated-p)
                              (parse-unicode-property)
                            (let ((matcher (list :property property)))
                              (values nil (if (eq (char= escaped #\P) property-negated-p)
                                              matcher
                                 (list :negate matcher))))))
                         ((#\d #\w #\s #\D #\W #\S)
                          (let ((matcher (shorthand-matcher escaped)))
                            (values nil (if (member escaped '(#\D #\W #\S))
                                            (list :negate matcher)
                                            matcher))))
                         (#\b (values (code-char 8) nil))
                         ((#\a #\f #\n #\r #\t #\v #\x #\u #\U)
                           (decf position)
                           (multiple-value-bind (character raw-octet-p)
                               (escaped-character)
                             (values character nil raw-octet-p)))
                         ((#\0 #\1 #\2 #\3 #\4 #\5 #\6 #\7)
                          (unless octal
                            (fail "Octal escapes are disabled" (1- position)))
                          (values (parse-octal-code (1- position)) nil
                                  (not (flag-p +flag-unicode+))))
                         ((#\8 #\9) (fail "Backreferences are not supported" (1- position)))
                         (otherwise
                          (when (ascii-alphanumeric-p escaped)
                            (fail "Invalid escape sequence" (1- position)))
                          (values escaped nil nil)))))
                   (values (take) nil nil)))
             (parse-class ()
               (take)
               (let ((negated-p (when (and (peek) (char= (peek) #\^)) (take))))
                   (when (at-end-p)
                     (fail "Unclosed character class"))
                   (if (char= (peek) #\])
                       (progn
                         (take)
                         (make-class nil negated-p nil))
                       (labels
                       ((next-class-token ()
                          (let ((saved-position position))
                            (when (raw-peek)
                              (incf position)
                              (prog1 (peek)
                                (setf position saved-position)))))
                        (set-operator ()
                          (let ((first (peek))
                                (second (next-class-token)))
                            (cond ((and first second
                                        (char= first #\&)
                                        (char= second #\&))
                                   :intersection)
                                  ((and first second
                                        (char= first #\~)
                                        (char= second #\~))
                                   :symmetric-difference)
                                  ((and first second
                                        (char= first #\-)
                                        (char= second #\-))
                                   :difference)
                                  (t nil))))
                        (consume-set-operator ()
                          (let ((operator (set-operator)))
                            (when operator
                              (take)
                              (peek)
                              (take))
                            operator))
                        (parse-union ()
                          (let ((ranges nil)
                                (matchers nil)
                                (saw-item-p nil))
                            (loop
                              (when (at-end-p) (fail "Unclosed character class"))
                              (when (or (char= (peek) #\]) (set-operator))
                                (return))
                              (setf saw-item-p t)
                              (let ((posix (parse-posix-class)))
                                (cond
                                  (posix
                                   (when ranges
                                     (push (ranges-matcher (nreverse ranges)) matchers)
                                     (setf ranges nil))
                                   (push posix matchers))
                                  ((char= (peek) #\[)
                                   (when ranges
                                     (push (ranges-matcher (nreverse ranges)) matchers)
                                     (setf ranges nil))
                                   (push (node-matcher (parse-class)) matchers))
                                       (t
                                   (multiple-value-bind (literal matcher raw-octet-p) (class-item)
                                     (cond
                                       (matcher
                                        (when ranges
                                          (push (ranges-matcher (nreverse ranges)) matchers)
                                          (setf ranges nil))
                                        (push matcher matchers))
                                       ((let ((current (peek)))
                                          (and current
                                               (char= current #\-)
                                               (let ((next (next-class-token)))
                                                 (and next
                                                      (not (char= next #\]))
                                                      (not (char= next #\-))))))
                                        (take)
                                        (peek)
                                        (multiple-value-bind (end end-matcher end-raw-octet-p) (class-item)
                                          (when end-matcher
                                            (fail "Character-class range endpoint must be literal"))
                                          (ensure-byte-class-character literal raw-octet-p)
                                          (ensure-byte-class-character end end-raw-octet-p)
                                          (when (> (char-code literal) (char-code end))
                                            (fail "Character-class range is reversed"))
                                          (push (range literal end) ranges)))
                                       (t
                                        (ensure-byte-class-character literal raw-octet-p)
                                        (push (range literal literal) ranges))))))))
                            (unless saw-item-p
                              (fail "Character-class set operation requires a right operand"))
                            (when ranges
                              (push (ranges-matcher (nreverse ranges)) matchers))
                            (union-matcher (nreverse matchers))))
                        (parse-expression ()
                          (let ((left (parse-union)))
                            (loop for operator = (consume-set-operator)
                                  while operator do
                              (setf left (list operator left (parse-union))))
                            left)))
                         (let ((matcher (parse-expression)))
                           (unless (and (peek) (char= (peek) #\]))
                             (fail "Unclosed character class"))
                           (take)
                           (make-class nil negated-p matcher))))))
             (read-group-name ()
               (let ((beginning position))
                 (unless (capture-name-start-p (peek))
                   (fail "Capture name must start with an alphabetic character or underscore"))
                 (loop while (and (peek)
                                  (capture-name-character-p (peek))) do
                   (incf position))
                 (let ((name (subseq pattern beginning position)))
                   (unless (and (peek) (char= (peek) #\>))
                     (fail "Unclosed capture name"))
                   (take)
                   (when (member name group-names :test #'string=)
                     (fail "Duplicate capture name" beginning))
                   (push name group-names)
                   name)))
             (parse-flags ()
               (let ((enabled-p t) (seen-p nil) (disabled-p nil)
                     (seen-flags nil))
                 (loop while (and (peek) (or (member (peek) '(#\i #\m #\s #\R #\U #\x #\u))
                                            (char= (peek) #\-))) do
                   (if (char= (peek) #\-)
                       (progn
                         (when disabled-p
                           (fail "Inline flags may contain only one -" position))
                         (take)
                         (setf enabled-p nil disabled-p t))
                       (let ((character (take)))
                         (when (member character seen-flags)
                           (fail "Duplicate inline flag" (1- position)))
                         (push character seen-flags)
                         (setf flags (update-parser-flag flags character enabled-p))
                         (setf seen-p t))))
                 (unless seen-p (fail "Expected inline flags"))))
             (parse-group ()
               (take)
               (with-parser-nesting
                   (nesting-depth nest-limit
                                  (fail "Regular expression exceeds the configured nesting limit"))
                 (let ((capture-index nil) (name nil) (capturing-p (not never-capture))
                     (scoped-flags-p nil))
                 (when (and (peek) (char= (peek) #\?))
                   (take)
                   (case (peek)
                     (#\: (take) (setf capturing-p nil))
                     (#\< (take) (setf name (read-group-name) capturing-p t))
                     (#\P
                      (take)
                      (unless (and (peek) (char= (peek) #\<))
                        (fail "Expected < after ?P"))
                      (take)
                      (setf name (read-group-name) capturing-p t))
                     (otherwise
                      (let ((saved-flags flags))
                        (parse-flags)
                        (case (peek)
                          (#\) (take) (return-from parse-group (make-concat nil)))
                          (#\: (take) (setf capturing-p nil scoped-flags-p saved-flags))
                          (otherwise (fail "Expected : or ) after inline flags")))))))
                 (when capturing-p
                   (setf capture-index (incf group-count)))
                 (let ((child (parse-alternation)))
                   (unless (and (peek) (char= (peek) #\)))
                     (fail "Unclosed group"))
                   (take)
                   (when scoped-flags-p (setf flags scoped-flags-p))
                   (make-instance 'group-node :child child :capture-index capture-index :name name)))))
             (parse-atom ()
               (when (at-end-p) (fail "Expected an expression"))
               (case (peek)
                 (#\( (parse-group))
                 (#\[ (parse-class))
                 (#\. (take) (make-instance 'any-char-node
                                               :dotall-p (flag-p +flag-dotall+)
                                               :crlf-p (flag-p +flag-crlf+)
                                               :line-terminator line-terminator
                                               :unicode-p (flag-p +flag-unicode+)))
                 (#\^ (take) (make-instance 'anchor-node :kind :start
                                              :multiline-p (flag-p +flag-multiline+)
                                              :crlf-p (flag-p +flag-crlf+)
                                              :line-terminator line-terminator))
                 (#\$ (take) (make-instance 'anchor-node :kind :end
                                              :multiline-p (flag-p +flag-multiline+)
                                              :crlf-p (flag-p +flag-crlf+)
                                              :line-terminator line-terminator))
                 (#\\ (take) (parse-escape))
                 ((#\* #\+ #\? #\} #\| #\)) (fail "Unexpected metacharacter"))
                 (otherwise (make-literal (take)))))
             (parse-quantifier (node)
               (let ((minimum nil) (maximum nil) (quantified-p nil))
                 (case (peek)
                   (#\* (take) (setf minimum 0 maximum nil quantified-p t))
                   (#\+ (take) (setf minimum 1 maximum nil quantified-p t))
                   (#\? (take) (setf minimum 0 maximum 1 quantified-p t))
                   (#\{ (take)
                        (setf minimum (parse-number) maximum minimum quantified-p t)
                        (cond ((and (peek) (char= (peek) #\,))
                               (take)
                               (setf maximum (unless (and (peek) (char= (peek) #\}))
                                               (parse-number))))
                              ((and (peek) (char= (peek) #\})) nil)
                              (t (fail "Expected , or } in repetition")))
                        (unless (and (peek) (char= (peek) #\}))
                          (fail "Unclosed repetition"))
                        (take)
                        (when (and maximum (> minimum maximum))
                          (fail "Repetition minimum exceeds maximum"))))
                 (if quantified-p
                     (let ((greedy-p (not (flag-p +flag-ungreedy+))))
                       (when (and (peek) (char= (peek) #\?))
                         (take)
                         (setf greedy-p (not greedy-p)))
                       (when (member (peek) '(#\* #\+ #\? #\{))
                         (fail "Repeated repetition operator"))
                       (make-instance 'repetition-node :child node :min minimum
                                      :max maximum :greedy-p greedy-p))
                     node)))
             (parse-concatenation ()
               (let ((children nil))
                 (loop until (or (at-end-p) (member (peek) '(#\| #\)))) do
                   (push (parse-quantifier (parse-atom)) children))
                 (make-concat (nreverse children))))
             (parse-alternation ()
               (let ((branches (list (parse-concatenation))))
                 (loop while (and (peek) (char= (peek) #\|)) do
                   (take)
                    (push (parse-concatenation) branches))
                   (if (null (cdr branches))
                       (car branches)
          (make-instance 'alternation-node :branches (nreverse branches))))))
       (let ((ast (if literal
                      (progn
                        (setf position length)
                        (make-concat
                         (loop for character across pattern
                               collect (make-literal character))))
                      (parse-alternation))))
         (unless (at-end-p) (fail "Unexpected trailing input"))
        ast))))
